(function(){
var sidebar='  <div class="sidebar">'
sidebar+='          <div class="sidebar_top"></div>'
sidebar+='          <div class="sidebar_item">'
sidebar+='            <h3>Recent Posts</h3>'
sidebar+='            <ul>'
sidebar+='        <li><a  href="debugging_tool.html">Debugging Tool</a></li>'         
sidebar+='	<li><a  href="debugger.html">Javascript Debugger</a></li>'
sidebar+='	<li><a  href="unbinding.html">Unbinding events (Backbone)</a></li>'
sidebar+='        <li><a  href="render_one_model.html">Rendering only one model at refresh</a></li>'
sidebar+='	<li><a  href="bindall.html">Bindall disadvantages</a></li>'
sidebar+='        <li><a  href="selenium_handler.html" >Selenium Handler</a></li>'
sidebar+='        <li><a  href="under_construction.html">Selenium Performance</a></li>'
sidebar+='        <li><a  href="under_construction.html">Selenium V.S Jasmine</a></li>'
sidebar+='        <li><a  href="under_construction.html">Selenium Server On Client side</a></li>'
sidebar+='        <li><a  href="under_construction.html">Jenkins execute on each commit</a></li>'
sidebar+='        <li><a  href="under_construction.html">html compile</a></li>'
sidebar+='        <li><a  href="under_construction.html">precommit</a></li>'
sidebar+='        <li><a  href="under_construction.html">Webdriver V.S Selenium</a></li>'
sidebar+='            </ul>'
sidebar+='          </div>'
sidebar+='          <div class="sidebar_base"></div>'
sidebar+='        </div>'
sidebar+='        <div class="sidebar">'
sidebar+='          <div class="sidebar_top"></div>'
sidebar+='          <div class="sidebar_item">'
sidebar+='            <h3>Latest News</h3>'
sidebar+='           <h4>New Website </h4>'
sidebar+='            <h5>January 1st, 2012</h5>'
sidebar+='            <p>There is no news for now on, but make sure you will check this out later.<br /><a href="#">Read more</a></p>'
sidebar+='          </div>'
sidebar+='          <div class="sidebar_base"></div>'
sidebar+='        </div>'
sidebar+='        <div class="sidebar">'
sidebar+='          <div class="sidebar_top"></div>'
sidebar+='          <div class="sidebar_item">'
sidebar+='            <h3>Search</h3>'
sidebar+='            <form method="post" action="#" id="search_form">'
sidebar+='              <p>'
sidebar+='                <input class="search" type="text" name="search_field" value="Enter keywords....." />'
sidebar+='                <input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;" src="style/search.png" alt="Search" title="Search" />'
sidebar+='              </p>'
sidebar+='            </form>'
sidebar+='          </div>'
sidebar+='          <div class="sidebar_base"></div>'
sidebar+='        </div>'

document.write(sidebar);
}())


