(function(){
var sidebar='  <div class="sidebar">'
sidebar+='          <div class="sidebar_top"></div>'
sidebar+='          <div class="sidebar_item">'
sidebar+='            <h3>Recent Posts</h3>'
sidebar+='            <ul>'
sidebar+='        <li><a  href="debugging_tool.html">Debugging Tool</a></li>'         
sidebar+='	<li><a  href="debugger.html">Javascript Debugger</a></li>'
sidebar+='	<li><a  href="unbinding.html">Unbinding events (Backbone)</a></li>'
sidebar+='        <li><a  href="renderonemodel.html">Rendering only one model at refresh</a></li>'
sidebar+='	<li><a  href="">Bindall disadvantages</a></li>'
sidebar+='        <li><a  href="selenium_handler.html" >Selenium Handler</a></li>'
sidebar+='        <li><a  href="">Selenium Performance</a></li>'
sidebar+='        <li><a  href="">Selenium V.S Jasmine</a></li>'
sidebar+='        <li><a  href="">Selenium Server On Client side</a></li>'
sidebar+='        <li><a  href="">Jenkins execute on each commit</a></li>'
sidebar+='        <li><a  href="">html compile</a></li>'
sidebar+='        <li><a  href="">precommit</a></li>'
sidebar+='        <li><a  href="">Webdriver V.S Selenium</a></li>'
sidebar+='            </ul>'
sidebar+='          </div>'
sidebar+='          <div class="sidebar_base"></div>'
sidebar+='        </div>'
sidebar+='        <div class="sidebar">'
sidebar+='          <div class="sidebar_top"></div>'
sidebar+='          <div class="sidebar_item">'
sidebar+='            <!-- insert your sidebar items here -->'
sidebar+='            <h3>Latest News</h3>'
sidebar+='           <h4>New Website Launched</h4>'
sidebar+='            <h5>January 1st, 2010</h5>'
sidebar+='            <p>2010 sees the redesign of our website. Take a look around and let us know what you think.<br /><a href="#">Read more</a></p>'
sidebar+='          </div>'
sidebar+='          <div class="sidebar_base"></div>'
sidebar+='        </div>'
sidebar+='        <div class="sidebar">'
sidebar+='          <div class="sidebar_top"></div>'
sidebar+='          <div class="sidebar_item">'
sidebar+='            <h3>Search</h3>'
sidebar+='            <form method="post" action="#" id="search_form">'
sidebar+='              <p>'
sidebar+='                <input class="search" type="text" name="search_field" value="Enter keywords....." />'
sidebar+='                <input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;" src="style/search.png" alt="Search" title="Search" />'
sidebar+='              </p>'
sidebar+='            </form>'
sidebar+='          </div>'
sidebar+='          <div class="sidebar_base"></div>'
sidebar+='        </div>'

document.write(sidebar);
}())


